\timing

DROP TABLE IF EXISTS SRC_chicago_311_graffiti_removal;
    
CREATE TABLE IF NOT EXISTS SRC_chicago_311_graffiti_removal(
CREATION_DATE DATE,
STATUS VARCHAR(20),
COMPLETION_DATE DATE,
SERVICE_REQUEST_NUMBER VARCHAR(25),
TYPE_OF_SERVICE_REQUEST VARCHAR(25),
WHAT_TYPE_OF_SURFACE_IS_THE_GRAFFITI_ON_ VARCHAR(45),
WHERE_IS_THE_GRAFFITI_LOCATED_ VARCHAR(35),
STREET_ADDRESS VARCHAR(60),
ZIP_CODE CHAR(5),
X_COORDINATE FLOAT8,
Y_COORDINATE FLOAT8,
WARD INTEGER,
POLICE_DISTRICT INTEGER,
COMMUNITY_AREA INTEGER,
SSA VARCHAR(10),
LATITUDE FLOAT8,
LONGITUDE FLOAT8,
LOCATION POINT,
PRIMARY KEY(SERVICE_REQUEST_NUMBER));
    
\copy SRC_chicago_311_graffiti_removal FROM '/home/alund/wopr/processed_data/dedup/dedup_chicago-311-graffiti_removal_2014-03-06.csv' WITH DELIMITER ',' CSV HEADER;
    
DROP TABLE IF EXISTS DAT_chicago_311_graffiti_removal;
    
CREATE TABLE IF NOT EXISTS DAT_chicago_311_graffiti_removal(
chicago_311_graffiti_removal_row_id SERIAL,
start_date DATE,
end_date DATE DEFAULT NULL,
current_flag BOOLEAN DEFAULT true,
CREATION_DATE DATE,
STATUS VARCHAR(20),
COMPLETION_DATE DATE,
SERVICE_REQUEST_NUMBER VARCHAR(25),
TYPE_OF_SERVICE_REQUEST VARCHAR(25),
WHAT_TYPE_OF_SURFACE_IS_THE_GRAFFITI_ON_ VARCHAR(45),
WHERE_IS_THE_GRAFFITI_LOCATED_ VARCHAR(35),
STREET_ADDRESS VARCHAR(60),
ZIP_CODE CHAR(5),
X_COORDINATE FLOAT8,
Y_COORDINATE FLOAT8,
WARD INTEGER,
POLICE_DISTRICT INTEGER,
COMMUNITY_AREA INTEGER,
SSA VARCHAR(10),
LATITUDE FLOAT8,
LONGITUDE FLOAT8,
LOCATION POINT,
PRIMARY KEY(chicago_311_graffiti_removal_row_id),
UNIQUE(SERVICE_REQUEST_NUMBER, start_date));
    
INSERT INTO DAT_chicago_311_graffiti_removal(
start_date,
CREATION_DATE,
STATUS,
COMPLETION_DATE,
SERVICE_REQUEST_NUMBER,
TYPE_OF_SERVICE_REQUEST,
WHAT_TYPE_OF_SURFACE_IS_THE_GRAFFITI_ON_,
WHERE_IS_THE_GRAFFITI_LOCATED_,
STREET_ADDRESS,
ZIP_CODE,
X_COORDINATE,
Y_COORDINATE,
WARD,
POLICE_DISTRICT,
COMMUNITY_AREA,
SSA,
LATITUDE,
LONGITUDE,
LOCATION)
SELECT
'2014-03-06' AS start_date,
CREATION_DATE,
STATUS,
COMPLETION_DATE,
SERVICE_REQUEST_NUMBER,
TYPE_OF_SERVICE_REQUEST,
WHAT_TYPE_OF_SURFACE_IS_THE_GRAFFITI_ON_,
WHERE_IS_THE_GRAFFITI_LOCATED_,
STREET_ADDRESS,
ZIP_CODE,
X_COORDINATE,
Y_COORDINATE,
WARD,
POLICE_DISTRICT,
COMMUNITY_AREA,
SSA,
LATITUDE,
LONGITUDE,
LOCATION
FROM SRC_chicago_311_graffiti_removal;
    
INSERT INTO DAT_Master(
start_date,
end_date,
current_flag,
Location,
LATITUDE,
LONGITUDE,
obs_date,
obs_ts,
dataset_name,
dataset_row_id)
SELECT
start_date,
end_date,
current_flag,
LOCATION,
LATITUDE,
LONGITUDE,
CREATION_DATE AS obs_date,
NULL AS obs_ts,
'chicago_311_graffiti_removal' AS dataset_name,
chicago_311_graffiti_removal_row_id AS dataset_row_id
FROM
DAT_chicago_311_graffiti_removal;
